# Site settings
title : Robinson Raju
author :
  name : Robinson Raju
  email : robinson.raju@gmail.com
  github : robinsonraju
  twitter : robinsonraju

production_url : http://robinsonraju.github.io

title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robinsonraju.github.io" # the base hostname & protocol for your site
twitter_username: robinsonraju
github_username:  robinsonraju

# Build settings
markdown: kramdown

