# Site settings
title: Rob's Notes
header-img: img/home-bg.jpg
email: robinson.raju@gmail.com
description: "Welcome to my site. "
baseurl: ""
url: "http://robinsonraju.github.io"
twitter_username: robinsonraju
github_username:  robinsonraju
facebook_username:  robinson.raju.165

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

